CREATE DATABASE CatalogoDeProdutos;
GO

USE CatalogoDeProdutos;
GO

CREATE TABLE Categorias(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(200) NOT NULL,
	Descricao VARCHAR(500),
	DataCriacao DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);

CREATE TABLE Produtos(
	Id  INT PRIMARY KEY IDENTITY(1,1),
	Nome VARCHAR(200) NOT NULL,
	Descricao VARCHAR(500),
	Preco DECIMAL(18,2) NOT NULL CHECK (Preco >= 0),
	CategoriaID INT NOT NULL,
	Ativo BIT NOT NULL DEFAULT 1,
	DataCriacao DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
	FOREIGN KEY (CategoriaID) REFERENCES Categorias(Id)
);
